#!/usr/bin/env python3
import sys
import os

path = os.path.dirname(os.path.abspath(__file__))
# Caminho fixo do projeto
project_dir = path

# Ativa venv
venv_python = os.path.join(project_dir, 'venv', 'bin', 'python3')
if os.path.exists(venv_python):
    if sys.executable != venv_python:
        os.execv(venv_python, [venv_python] + sys.argv)

# Adiciona projeto ao path
sys.path.insert(0, project_dir)

# Importa e executa
from main import main

if __name__ == "__main__":
    main()
